version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: store_rating
      POSTGRES_PASSWORD: store_rating_pw
      POSTGRES_DB: store_rating_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
